config/routes.rb
Rails.application.routes.draw do
  resources :communities do
    resources :posts
  end
  devise_for :users, controllers: {
    confirmations: 'confirmations',
    omniauth_callbacks: 'users/omniauth',
  }

  resources :apples

  # resources :users, only: [:index, :show, :edit, :update] do
  #  member do 
  #    delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
  #  end
  # end

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/users', to: redirect('home#index')

  get '/search', to: "communities#search"

  get '/admin', to: "profiles#admin"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :subscriptions
  resources :votes
  resources :comments
  resources :profiles

  resources :dashboard, only: [:index]
  resources :home, only: [:index]
  root to: "home#index"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!, except: [:show]

    def show
        @user = User.find_by(id: params[:id])
        @posts = Post.where(user_id: @user.id)
    end

    def admin
        if ! current_user.admin?
            respond_to do |format|
                format.html { redirect_to root_path, notice: 'You need to be an admin to access admin panel.' }
                format.json { head :no_content }
              end  
        end
        @users = User.where.not(email: current_user.email)
        @communities = Community.all
        @posts = Post.all
    end

    private

end

app/views/profiles/admin.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-lg-4 card">
      <h3 class="text-muted mb-2">All Users</h3>
      <% @users.each do |u| %>
        <h4><%= u.email %></h4>
        <%= link_to "Delete this user", apple_path(u.id), class: "btn btn-sm btn-danger mb-5", data: { confirm: 'Are you sure?' }, method: :delete %>
      <% end %>
    </div>
    <div class="col-lg-4 card">
      <h3 class="text-muted mb-2">All Communities</h3>
      <% @communities.each do |c| %>
        <h4><%= c.name %></h4>
        <%= link_to "Delete this community", community_path(c.id), class: "btn btn-sm btn-danger mb-5", data: { confirm: 'Are you sure?' }, method: :delete %>
      <% end %>
    </div>
    <div class="col-lg-4 mb-2 card">
      <h3 class="text-muted">All Posts</h3>
      <% @posts.each do |p| %>
      <h4><%= p.title %></h4>
      <%= link_to "Delete this post", community_post_path(p.community, p), class: "btn btn-sm btn-danger mb-5", data: { confirm: 'Are you sure?' }, method: :delete %>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8 text-center">
            <h1><% if @user.avatar.present? %>
                <%= image_tag @user.avatar.url, :size => "50x50", class: "rounded-circle mr-2" %>
            <% end %>
            <%= @user.username %>s' profile</h1>
            <h4 class="text-muted mt-5">Bio:</h4>
            <p><% if @user.bio.present? %><%= @user.bio %><% else %>This User dosen't have a bio yet.<% end %></p>
            <h5 class="text-muted mt-5"><%= @user.username %>s' posts:</h5>
            <% @posts.each do |post| %>
                <div class="card my-4 shadow-sm">
                <div class="card-title my-2">
                    <div class="row">
                    <div class="col-md-3 text-md-left px-4">
                        <span class="text-muted">r/</span><%= link_to post.community.name, post.community %>
                    </div>
                    <div class="col-md-6 text-md-center">
                        <h4 class="px-4"><%= link_to post.title, community_post_path(post.community_id, post) %></h4>
                    </div>
                    <div class="col-md-3 text-md-right px-4">
                    By <span class="text-muted"> u/</span><%= link_to post.user.username, profile_path(post.user_id) %>
                    </div>
                    </div>
                </div>
                    <% if post.image.present? %>
                    <%= image_tag post.image.url, class: "img-fluid", style: "height: 25rem;" %>
                    <% end %>
                <div class="card-body">
                    <p class="card-text" style="overflow: hidden; height: 6rem;"><%= post.post %></p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group align-middle">
                        <%= link_to "Total votes:" + post.votes.count.to_s, community_post_path(post.community_id, post), class: "text-info" %>
                        </div>
                        <small class="text-muted">Posted <%= time_ago_in_words(post.created_at) %> ago</small>
                    </div>
                </div>
                </div>
            <% end %>
        </div>
        <div class="col-lg-2"></div>
    </div>
</div>