config/routes.rb
Rails.application.routes.draw do
  resources :communities do
    resources :posts
  end
  devise_for :users, controllers: {
    confirmations: 'confirmations',
    omniauth_callbacks: 'users/omniauth',
  }

  resources :apples

  # resources :users, only: [:index, :show, :edit, :update] do
  #  member do 
  #    delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
  #  end
  # end

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/users', to: redirect('home#index')

  get '/search', to: "communities#search"

  get '/admin', to: "profiles#admin"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :subscriptions
  resources :votes
  resources :comments
  resources :profiles

  resources :dashboard, only: [:index]
  resources :home, only: [:index]
  root to: "home#index"
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :post, :user_id, :community_id
  belongs_to :community
  belongs_to :user

  mount_uploader :image, IconUploader

  has_many :votes, dependent: :destroy
  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @community= Community.find(params[:community_id])
    @vote = Vote.new
    @already_voted = user_signed_in? ? Vote.where(post_id: @post.id, user_id: current_user.id).any? : false
    @is_upvote = user_signed_in? ? Vote.where(post_id: @post.id, user_id: current_user.id, upvote: 'true').any? : false
    @upvotes = Vote.where(post_id: @post.id, upvote: 'true').count
    @downvotes = Vote.where(post_id: @post.id, upvote: 'false').count
    @score = @upvotes - @downvotes
    @comments = Comment.where(post_id: @post.id)
  end

  # GET /posts/new
  def new
    @community = Community.find(params[:community_id])
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @community = Community.find(params[:community_id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.community_id = params[:community_id]

    respond_to do |format|
      if @post.save
        format.html { redirect_to community_path(@post.community_id), notice: 'Post was successfully created.' }
        # format.json { render :show, status: :created, location: @post }
      else
        @community = Community.find(params[:community_id])
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to community_post_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @community = @post.community
    @votes = Vote.where(post_id: @post.id)
    @votes.each do |vote|
      vote.destroy
    end
    @comments = Comment.where(post_id: @post.id)
    @comments.each do |comment|
      comment.destroy
    end

    @post.destroy
    respond_to do |format|
      format.html { redirect_to community_path(@community), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:community_id, :title, :post, :image, :image_cache)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_downvote.html.erb
<%= form_for @vote do |f| %>
    <%= f.hidden_field :community_id, value: community_id %>
    <%= f.hidden_field :post_id, value: post_id %>
    <%= f.hidden_field :upvote, value: 'false' %>
    <%= button_tag( :class => "btn btn-primary") do %>
        <i data-feather="arrow-down-circle"></i>
    <% end %>
<% end %>

app/views/posts/_form.html.erb
<%= form_for [@community, @post] do |form| %>
  <div class="form-group">
    <p class="text-muted m-0"><%= label_tag :title %></p>
    <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>

  <div class="form-group">
    <p class="text-muted m-0"><%= label_tag :post %></p>
    <%= form.text_area :post, class: "form-control", placeholder: "Whats on your mind?" %>
  </div>

  <% if @post.image.present? %>
    <%= image_tag @post.image.url, :size => "100x100", class: "rounded-circle mt-5" %>
  <% end %>
  <div class="form-group">
    <p class="text-muted m-0"><%= form.label :image %></p>
    <%= form.file_field :image, class: "form-control" %>
    <%= form.hidden_field :image_cache %>
  </div>

  <%= form.submit "Submit", class: "btn btn-success" %>

<% end %>

app/views/posts/_upvote.html.erb
<%= form_for @vote do |f| %>
    <%= f.hidden_field :community_id, value: community_id %>
    <%= f.hidden_field :post_id, value: post_id %>
    <%= f.hidden_field :upvote, value: 'true' %>
    <%= button_tag( :class => "btn btn-danger mr-2") do %>
        <i data-feather="arrow-up-circle"></i>
    <% end %>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4 text-center">
        <h3 class="text-muted mb-5">Edit Post</h3>
            <%= render 'form', post: @post %>
        </div>
        <div class="col-lg-4 text-center">
            <%= link_to 'Back', community_post_path, class: "btn btn-outline-secondary" %>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Community</th>
      <th>Tittle</th>
      <th>Post</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.community_id %></td>
        <td><%= post.tittle %></td>
        <td><%= post.post %></td>
        <td><%= post.image %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4 text-center">
        <h3 class="text-muted mb-5">New Post</h3>
            <%= render 'form', post: @post %>
        </div>
        <div class="col-lg-4 text-center">
            <%= link_to 'Back', community_path(@community), class: "btn btn-outline-secondary" %>
        </div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2 text-center">
      <%= link_to "Back to Community", @community, class: "btn btn-outline-dark" %>
    </div>
    <div class="col-lg-8 text-center">
         <div class="card mb-4 shadow-sm">
          <div class="card-title my-2">
              <div class="row">
              <div class="col-md-3 text-md-left px-4">
              <a href="">
                  <span class="text-muted">r/</span><%= link_to @community.name, @community %></a>
              </div>
              <div class="col-md-6 text-md-center">
                  <h4 class="px-4"><%= @post.title %></h4>
              </div>
              <div class="col-md-3 text-md-right px-4">
              By <span class="text-muted"> u/</span><%= link_to @post.user.username, profile_path(@post.user_id) %>
              </div>
              </div>
          </div>
            <% if @post.image.present? %>
              <%= image_tag @post.image.url, class: "img-fluid", style: "height: 25rem;" %>
            <% end %>
          <div class="card-body">
              <p class="card-text"><%= @post.post %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group align-middle">
                <% if ! user_signed_in? %>
                  <%= link_to "Sign in to vote.", new_user_session_path, class: "btn btn-sm btn-outline-info" %>
                <% else %>
                  <% if ! @already_voted %>
                  <%= render partial: "posts/upvote", locals: { community_id: @community.id, post_id: @post.id } %>
                  <%= render partial: "posts/downvote", locals: { community_id: @community.id, post_id: @post.id } %>
                  <% else %>
                    <small class="text-muted mr-2">Delete your vote</small>
                    <%= link_to vote_path, method: :delete do %>
                      <i data-feather="trash-2" class="text-dark"></i>
                    <% end %>
                  <% end %>
                <% end %>
                  <span class="font-weight-bold mx-2 <% if @score > 0%>text-danger<% else %>text-primary<% end %>">Score: <%= @score %></span>
                </div>
                <small class="text-muted">Posted <%= time_ago_in_words(@post.created_at) %> ago</small>
              </div>
          </div>
        </div>
        <h3 class="text-muted">Comments</h3>
        <% @comments.each do |comment| %>
          <div class="card text-left mb-3">
          <% if comment.user.avatar? %>
              <%= image_tag comment.user.avatar.url, :size => "25x25", class: "rounded-circle float-left ml-1 mt-3" %>
          <% end %>
            <span class="ml-1 mb-3">u/<%= comment.user.username %> said:</span>

            <p class="text-center"><%= comment.text %></p>

            <p class="text-muted text-right mr-1"><% if user_signed_in? && comment.user_id == current_user.id %> <%= link_to comment_path, method: :delete do %><i data-feather="trash-2" class="text-dark"></i><% end %> <% end %><small>Commented <%= time_ago_in_words(comment.created_at) %> ago</small></p>
          </div>
        <% end %>
    </div>
    <div class="col-lg-2 text-center">
      <% if user_signed_in? %>
        <%= link_to "Comment", new_comment_path(:post_id => @post.id), class: "btn btn-info mb-2" %>
      <% end %>
      <% if user_signed_in? && @post.user_id == current_user.id %>
        <%= link_to "Edit my post", edit_community_post_path, class: "btn btn-success mb-2" %>
        <%= link_to "Delete my post", community_post_path(@post.community, @post), class: "btn btn-danger", data: { confirm: 'Are you sure?' }, method: :delete %>
      <% end %>
    </div>
  </div>
</div>