config/routes.rb
Rails.application.routes.draw do
  resources :communities do
    resources :posts
  end
  devise_for :users, controllers: {
    confirmations: 'confirmations',
    omniauth_callbacks: 'users/omniauth',
  }

  resources :apples

  # resources :users, only: [:index, :show, :edit, :update] do
  #  member do 
  #    delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
  #  end
  # end

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/users', to: redirect('home#index')

  get '/search', to: "communities#search"

  get '/admin', to: "profiles#admin"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :subscriptions
  resources :votes
  resources :comments
  resources :profiles

  resources :dashboard, only: [:index]
  resources :home, only: [:index]
  root to: "home#index"
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :user

  mount_uploader :icon, IconUploader

  validates_presence_of :user_id, :name, :description
  has_many :posts
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions, source: :user

end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_user!, except: [ :index ,:show ]
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  def search
    @no_search = true
    if params[:search].blank?
      @no_search = false
    else
      @parameter = params[:search].downcase
      @results = Community.all.where("lower(name) LIKE :search", search: "%#{@parameter}%")
    end
  end
  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.all
    @communities = Community.order(created_at: :desc)
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
    @posts = @community.posts
    @posts = @community.posts.order(created_at: :desc)
    @subscriber_count = @community.subscribers.count
    @is_subscribed = user_signed_in? ? Subscription.where(community_id: @community.id, user_id: current_user.id).any? : false
    @subscription = Subscription.new
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params)
    @community.user_id = current_user.id

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @posts = Post.where(community_id: @community.id)
    @posts.each do |post|
      @votes = Vote.where(post_id: post.id)
      @votes.each do |vote|
        vote.destroy
      end
      @comments = Comment.where(post_id: post.id)
      @comments.each do |comment|
        comment.destroy
      end
      post.destroy
    end

    @subscriptions = Subscription.where(community_id: @community.id)
    @subscriptions.each do |subscription|
      subscription.destroy
    end

    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def community_params
      params.require(:community).permit(:user_id, :name, :description, :icon, :icon_cache)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.erb
<%= form_for @community do |form| %>
  <div class="form-group">
    <p class="text-muted m-0"><%= label_tag :name %></p>
    <%= form.text_field :name, class: "form-control", placeholder: "Name" %>
  </div>

  <div class="form-group">
    <p class="text-muted m-0"><%= label_tag :description %></p>
    <%= form.text_area :description, class: "form-control", placeholder: "Description" %>
  </div>

  <% if @community.icon.present? %>
    <%= image_tag @community.icon.url, :size => "100x100", class: "rounded-circle mt-5" %>
  <% end %>
  <div class="form-group">
    <p class="text-muted m-0"><%= form.label :icon %></p>
    <%= form.file_field :icon, class: "form-control" %>
    <%= form.hidden_field :icon_cache %>
  </div>

  <%= form.submit "Submit", class: "btn btn-success" %>

<% end %>

app/views/communities/_subscribe.html.erb
<%= form_for @subscription do |f| %>
    <%= f.hidden_field :community_id, value: community_id %>
    <%= f.submit "SUBSCRIBE", class: "btn btn-success my-2" %>
<% end %>

app/views/communities/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4 text-center">
        <h3 class="text-muted mb-5">Editing Community</h3>
            <%= render 'form', community: @community %>
        </div>
        <div class="col-lg-4 text-center">
            <%= link_to 'Back', @community, class: "btn btn-outline-secondary" %>
        </div>
    </div>
</div>

app/views/communities/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8 text-center">
    <h1>Communities</h1>
      <% @communities.each do |community| %>
      <div class="card mx-auto my-5" style="width: 20rem;">
        <h3 class="card-title mt-3">
        <% if community.icon.present? %>
          <%= image_tag community.icon.url, :size => "50x50", class: "rounded-circle" %>
        <% end %>
        <%= link_to community.name, community %>
        </h3>
        <p class="card-text mb-3" style="overflow: hidden; height: 6rem;"><%= community.description %></p>
        <p class="card-text"><em><small class="text-muted">The community is <%= time_ago_in_words(community.created_at) %> old</small></em></p>
      </div>
      <% end %>
    </div>
    <div class="col-lg-2 text-center"><%= link_to 'New Community', new_community_path, class: "btn btn-outline-primary" %></div>
  </div>
</div>

app/views/communities/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4 text-center">
        <h3 class="text-muted mb-5">New Community</h3>
            <%= render 'form', community: @community %>
        </div>
        <div class="col-lg-4 text-center">
            <%= link_to 'Back', communities_path, class: "btn btn-outline-secondary" %>
        </div>
    </div>
</div>

app/views/communities/search.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8 text-center">
            <%= form_tag(search_path, :method => "get") do %>
                <div class="form-group">
                    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
                </div>
                <%= button_tag "Search", class: "btn btn-info" %>
            <% end %>
            <% if @no_search %>
                <h3 class="text-muted mt-5">Search results</h3>
                <% @results.each do |result| %>
                    <p class="my-4"><%= link_to result.name, community_path(result.id), class: "h4" %></p>
                <% end %>
            <% end %>
        </div>
        <div class="col-lg-2"></div>
    </div>
</div>

app/views/communities/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2 text-center">
    </div>
    <div class="col-lg-8 text-center">
    <h1>
      <% if @community.icon.present? %>
        <%= image_tag @community.icon.url, :size => "50x50", class: "rounded-circle" %>
      <% end %>
      <%= @community.name %></h1>
        <h3 class="text-muted mt-3">About this Community</h3>
        <p class="mb-5"><%= @community.description %></p>
      <h3 class="text-muted">All Posts</h3>
      <% if @posts.count <= 0 %>
        <h5 class="text-muted mt-5">No posts yet.</h5>
      <% end %>
      <% @posts.each do |post| %>
         <div class="card mb-4 shadow-sm">
          <div class="card-title my-2">
              <div class="row">
              <div class="col-md-3 text-md-left px-4">
                <span class="text-muted">r/</span><%= link_to @community.name, @community %>
              </div>
              <div class="col-md-6 text-md-center">
                  <h4 class="px-4"><%= link_to post.title, community_post_path(@community, post) %></h4>
              </div>
              <div class="col-md-3 text-md-right px-4">
              By <span class="text-muted"> u/</span><%= link_to post.user.username, profile_path(post.user_id) %>
              </div>
              </div>
          </div>
            <% if post.image.present? %>
              <%= image_tag post.image.url, class: "img-fluid", style: "height: 25rem;" %>
            <% end %>
          <div class="card-body">
              <p class="card-text" style="overflow: hidden; height: 6rem;"><%= post.post %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group align-middle">
                  <%= link_to "Total votes:" + post.votes.count.to_s, community_post_path(@community, post), class: "text-info" %>
                </div>
                <small class="text-muted">Posted <%= time_ago_in_words(post.created_at) %> ago</small>
              </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-lg-2 text-center">
    <% if user_signed_in? %>
      <% if @community.user_id == current_user.id %>
        <%= link_to "Edit my community", edit_community_path, class: "btn btn-success mb-2" %>
        <%= link_to "Delete my community", community_path, class: "btn btn-danger mb-2", data: { confirm: 'Are you sure?' }, method: :delete %>
      <% end %>
    <% end %>
    <p class="text-muted">About this community</p>
    <p class=""><em><small class="text-muted">created <%= time_ago_in_words(@community.created_at) %> ago</small></em></p>
    <% if @is_subscribed %>
      <%= link_to "UNSUBSCRIBE", subscription_path, method: :delete, class: "btn btn-outline-danger my-2" %>
    <% else %>
      <%= render partial: "communities/subscribe", locals: { community_id: @community.id } %>
    <% end %>
    <p class="mt-2 mb-5"><%= pluralize @subscriber_count, "member" %></p>
    <% if @is_subscribed %>
    <%= link_to "Create new post", new_community_post_path(@community), class: "btn btn-primary" %>
    <% else %>
    <p>Subscribe to make a post.</p>
    <% end %>
    <p><%= link_to 'See all communities', communities_path, class: "btn btn-outline-dark mt-5" %></p>
    </div>
  </div>
</div>