config/routes.rb
Rails.application.routes.draw do
  resources :communities do
    resources :posts
  end
  devise_for :users, controllers: {
    confirmations: 'confirmations',
    omniauth_callbacks: 'users/omniauth',
  }

  resources :apples

  # resources :users, only: [:index, :show, :edit, :update] do
  #  member do 
  #    delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
  #  end
  # end

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/users', to: redirect('home#index')

  get '/search', to: "communities#search"

  get '/admin', to: "profiles#admin"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :subscriptions
  resources :votes
  resources :comments
  resources :profiles

  resources :dashboard, only: [:index]
  resources :home, only: [:index]
  root to: "home#index"
end

app/views/layouts/_footer.html.erb
<div class="container text-center fixed-bottom">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
            <p class="text-muted">© Tim Jevšenak</p>
        </div>
        <div class="col-lg-4"></div>
    </div>
</div>

app/views/layouts/_header.html.erb
<div class="container mb-5">
    <div class="row">
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <%= link_to "ReadIt", home_index_path, class: "navbar-brand" %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
            <% if user_signed_in? %>
               <ul class="navbar-nav ml-auto">
               <% if @header_user.admin? %>
                <li class="nav-item">
                    <%= link_to "Admin panel", admin_path, class: "btn btn-sm btn-light mr-3" %>
                </li>
                <% end %>
               <% if @header_user.avatar.present? %>
                    <li class="nav-item">
                        <%= image_tag @header_user.avatar.url, :size => "40x40", class: "rounded-circle mr-3" %>
                    </li>
                <% end %>
                <% if @header_user.username.present? %>
                    <li class="nav-item">
                        <%= link_to @header_user.username + "s' account", edit_user_registration_path, class: "btn btn-sm btn-secondary mr-2 mb-sm-2", style: "text-decoration: none;" %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-sm btn-secondary mr-2 mb-sm-2", style: "text-decoration: none;" %>
                    </li>
                <% end %>
                    <li class="nav-item">
                        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-sm btn-light", style: "text-decoration: none;" %>
                    </li>
                </ul> 
            <% else %>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <%= link_to "Log In", new_user_session_path, class: "btn btn-sm btn-secondary mr-2 mb-sm-2", style: "text-decoration: none;" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-sm btn-light", style: "text-decoration: none;" %>
                </li>
            </ul>
            <% end %>
            </div>
        </nav>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Read-It</title>
    <%= favicon_link_tag asset_path('logo.jpg') %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://unpkg.com/feather-icons"></script>
  </head>

  <body>
    <%= render partial: "layouts/header" %>

    <p class="alert"></p>

    <% if notice %>
    <div class="container"><div class="row"><div class="col-lg-4"></div><div class="col-lg-4"><p class="notice alert alert-success"><%= notice %></p></div><div class="col-lg-4"></div></div></div>
    <% end %>
    <% if alert %>
    <div class="container"><div class="row"><div class="col-lg-4"></div><div class="col-lg-4"><p class="alert alert-danger"><%= alert %></p></div><div class="col-lg-4"></div></div></div>
    <% end %>

    <%= yield %>
    <div class="mb-5"></div>
    <%= render partial: "layouts/footer" %>

    <script>
      feather.replace()
    </script>
    
  </body>
</html>